# cmake -DINPUT=<blob> -DOUTPUT=<hpp> -DIDENT=<name> -P bin2cpp.cmake
# Renders a binary blob as a generated constexpr std::byte array. The
# portable stand-in for #embed until MSVC grows it.
file(READ "${INPUT}" hex HEX)
file(SIZE "${INPUT}" size)
string(REGEX REPLACE "(..)" "std::byte{0x\\1}," bytes "${hex}")
file(WRITE "${OUTPUT}"
"#pragma once

#include <array>
#include <cstddef>

// generated by bin2cpp.cmake from ${INPUT} -- do not edit
inline constexpr std::array<std::byte, ${size}u> ${IDENT}{
  ${bytes}
};
")
