"""The build's identity: what engine.py stamped, as macros a project reads."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from .embed import write_if_changed
from .options import macro_value, refused_characters

# The mirror of options.py for what the build IS rather than what it was
# asked for. The rendered cmake machinery calls this module (`python -m
# buildutil.buildinfo`) with the json engine._stamp_build_info() wrote.

# Field to the value that stands in for it, in macro order. A build
# outside git, and a json that is missing or unreadable, land here.
NEUTRAL = {"version": "unknown", "commit": "unknown", "tag": "",
           "time": "", "dirty": False, "number": 0}


SEMVER = re.compile(r"(\d+)\.(\d+)\.(\d+)")


def package_macros(prefix: str, package: str) -> dict[str, str | int]:
  """The package version and its three numbers; anything not x.y.z-led reads as 0.0.0."""
  semver = SEMVER.match(package)
  parts = [int(part) for part in semver.groups()] if semver else [0, 0, 0]
  return {f"{prefix}_PACKAGE_VERSION": package if semver else "0.0.0",
          **{f"{prefix}_PACKAGE_VERSION_{name}": part
             for name, part in zip(("MAJOR", "MINOR", "PATCH"), parts)}}


def macro_name(prefix: str, field: str) -> str:
  return f"{prefix}_BUILD_{field.upper()}"


def _value(field: str, raw, neutral):
  """One stamped field in the kind its neutral value declares."""
  if isinstance(neutral, bool):
    return bool(raw)
  if isinstance(neutral, int):
    try:
      return int(raw)
    except (TypeError, ValueError):
      raise ValueError(f"build {field} is a number -- not {raw!r}") from None
  text = str(raw)
  refused = refused_characters(text)
  if refused:
    raise ValueError(f"build {field} may not hold {refused!r} -- the value "
                     "travels through a cmake string on its way to the "
                     "compiler")
  return text


def values(stamped: dict) -> dict:
  return {field: _value(field, stamped.get(field, neutral), neutral)
          for field, neutral in NEUTRAL.items()}


def stamp(path) -> dict:
  """The stamped json; a build that never stamped one is not an error --
  the cmake side says so and the neutral values stand in."""
  try:
    stamped = json.loads(Path(path).read_text(encoding="utf-8"))
  except (OSError, ValueError):
    stamped = {}
  return stamped if isinstance(stamped, dict) else {}


def read(path) -> dict:
  """The stamped json as the six fields."""
  return values(stamp(path))


def header_text(prefix: str, fields: dict, package: dict | None = None) -> str:
  macros = {macro_name(prefix, field): value for field, value in fields.items()}
  defines = "\n".join(f"#define {name} {macro_value(value)}"
                      for name, value in {**macros, **(package or {})}.items())
  return f"""\
// Generated by buildutil -- do not edit, and do not commit.
// The build's identity, from _bdudata/buildinfo.json. Included by hand:
// the time moves every build, and a force include would rebuild every TU.
#pragma once

{defines}
"""


def write_header(path, prefix: str, fields: dict, package: dict | None = None) -> Path:
  path = Path(path)
  write_if_changed(path, header_text(prefix, fields, package))
  return path


def main(argv: list[str] | None = None) -> int:
  parser = argparse.ArgumentParser(
    prog="buildutil.buildinfo", description=__doc__.splitlines()[0])
  parser.add_argument("--prefix", required=True)
  parser.add_argument("--package-prefix", default="")
  parser.add_argument("--input", required=True, type=Path)
  parser.add_argument("--output", required=True, type=Path)
  args = parser.parse_args(argv)
  stamped = stamp(args.input)
  package = (package_macros(args.package_prefix, _value("package", stamped.get("package", ""), ""))
             if args.package_prefix else None)
  write_header(args.output, args.prefix, values(stamped), package)
  return 0


if __name__ == "__main__":
  try:
    sys.exit(main())
  except ValueError as error:
    sys.exit(f"buildutil.buildinfo: {error}")
