"""Generate the resource-embedding translation unit for a declared set.

Invoked by the cmake machinery (`_buildutil_add_embedded_resources`) as
`"${BUILDUTIL_PY}" -m buildutil.embed --manifest ...`, never by hand.

TWO BACK ENDS, ONE HEADER. The accessor a project writes against is the
same either way; which one runs is decided in cmake by an actual compile
probe, not a version table:

  * `#embed` (C++26, gcc >= 15, clang >= 19, Apple clang 21) -- the .cpp
    holds one `#embed "<abs path>"` per resource and the compiler reads
    the bytes. Nothing large passes through this script or through the
    C++ parser as text.
  * a generated byte ARRAY -- the fallback, and the only path on MSVC
    (no `#embed` as of VS 2026). `static const unsigned char[]` rather
    than a string literal: MSVC caps a string literal at 16 KB, and
    there is no cap on an array initializer.

Both produce the same bytes, byte for byte; the tests assert it rather
than trusting it.

CCACHE. buildutil puts ccache in front of every compile, and ccache's
direct mode hashes a source and its #includes -- NOT what `#embed`
pulls in. Editing a resource then produced a byte-identical binary
(found in xoctet). So the generated .cpp always carries a DIGEST of
every embedded file, in a form the preprocessor keeps (a constexpr
string, not a comment): the bytes change, the digest changes, the
preprocessed source changes, and the cache cannot hit. The fallback
path carries the bytes themselves and would be safe anyway; the digest
is written on both so there is one story, not two.
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

# Enough of a content-type map to serve a UI over a scheme handler
# (which is what asked for it), and nothing more -- a project with an
# exotic extension names it in buildutil.toml rather than waiting for
# this table to grow.
MIME_TYPES = {
  ".bin": "application/octet-stream",
  ".css": "text/css",
  ".csv": "text/csv",
  ".gif": "image/gif",
  ".htm": "text/html",
  ".html": "text/html",
  ".ico": "image/vnd.microsoft.icon",
  ".jpeg": "image/jpeg",
  ".jpg": "image/jpeg",
  ".js": "text/javascript",
  ".json": "application/json",
  ".map": "application/json",
  ".md": "text/markdown",
  ".mjs": "text/javascript",
  ".mp3": "audio/mpeg",
  ".mp4": "video/mp4",
  ".otf": "font/otf",
  ".pdf": "application/pdf",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".ttf": "font/ttf",
  ".txt": "text/plain",
  ".wasm": "application/wasm",
  ".webm": "video/webm",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".xml": "application/xml",
  ".zip": "application/zip",
}
DEFAULT_MIME = "application/octet-stream"

BYTES_PER_LINE = 16


def mime_for(name: str, overrides: dict[str, str]) -> str:
  suffix = Path(name).suffix.lower()
  return overrides.get(suffix) or MIME_TYPES.get(suffix, DEFAULT_MIME)


def read_manifest(path: Path) -> list[tuple[str, Path]]:
  """<name>\\t<absolute path>, one per line, written by cmake at
  configure time. A file rather than argv: a resource dir with a few
  hundred files blows past the command-line limit on Windows, and the
  manifest doubles as the DEPENDS entry that re-runs this script when
  the SET changes (as opposed to the contents)."""
  entries = []
  for line in path.read_text(encoding="utf-8").splitlines():
    if not line.strip():
      continue
    name, _, source = line.partition("\t")
    entries.append((name, Path(source)))
  return entries


def cxx_string(text: str) -> str:
  escaped = text.replace("\\", "\\\\").replace('"', '\\"')
  return f'"{escaped}"'


def namespace_open(ns: str) -> str:
  return f"namespace {ns} {{"


def namespace_close(ns: str) -> str:
  return f"}}  // namespace {ns}"


def header_text(ns: str, names: list[str]) -> str:
  listed = "\n".join(f"//   {name}" for name in names) or "//   (none)"
  return f"""\
// Generated by buildutil -- do not edit, and do not commit.
//
// The resources declared for this module, compiled INTO the binary. The
// accessors below are the whole API and they do not touch the
// filesystem: whichever back end produced this file, the bytes are in
// the executable.
//
// Embedded here:
{listed}
//
// C++20: std::span and std::string_view. The declaring library carries
// that as a PUBLIC compile feature, so including this header never needs
// a project to say anything about standards.
#pragma once

#include <cstddef>
#include <span>
#include <string_view>

{namespace_open(ns)}

struct Resource {{
  // The declared name: the path under the resource directory, with '/'
  // separators on every platform.
  std::string_view name;
  // Guessed from the extension (a scheme handler has to serve one);
  // "application/octet-stream" when the extension says nothing.
  std::string_view mime;
  // The bytes. `data` is null exactly when the file is empty.
  const unsigned char* data;
  std::size_t size;

  std::span<const std::byte> bytes() const noexcept {{
    return {{reinterpret_cast<const std::byte*>(data), size}};
  }}
}};

// Every resource, sorted by name.
std::span<const Resource> all() noexcept;

// The named resource, or nullptr when nothing was embedded under that
// name. This is the accessor that distinguishes "absent" from "empty".
const Resource* find(std::string_view name) noexcept;

// The bytes of the named resource, or an EMPTY span -- which an
// embedded empty file yields too. Use find() when the difference
// matters.
std::span<const std::byte> get(std::string_view name) noexcept;

{namespace_close(ns)}
"""


def digest_lines(entries: list[tuple[str, Path]]) -> list[str]:
  """One SHA-256 per resource, as a constexpr the preprocessor keeps.
  See the module docstring: this is what stops ccache serving a stale
  object after a resource edit."""
  lines = []
  for name, source in entries:
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    lines.append(f"    {cxx_string(f'{name} {digest}')},")
  return lines


def array_body(source: Path) -> str:
  data = source.read_bytes()
  out = []
  for start in range(0, len(data), BYTES_PER_LINE):
    chunk = data[start:start + BYTES_PER_LINE]
    out.append("  " + "".join(f"{byte:#04x}," for byte in chunk))
  return "\n".join(out)


def source_text(ns: str, entries: list[tuple[str, Path]],
                overrides: dict[str, str], embed: bool) -> str:
  back_end = "#embed" if embed else "generated byte arrays"
  # `#embed` is C++26; gcc and clang implement it in every mode and say
  # so under -pedantic. This file is GENERATED, and a project building
  # -Werror did not ask to be told about a spelling it never wrote.
  pedantry = """
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wc23-extensions"
#elif defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wc++26-extensions"
#endif
""" if embed else ""
  chunks = [f"""\
// Generated by buildutil -- do not edit, and do not commit.
// Back end: {back_end}.
{pedantry}#include "resources.hpp"

#include <algorithm>
#include <cstddef>
#include <span>
#include <string_view>

{namespace_open(ns)}
namespace {{
"""]
  for index, (name, source) in enumerate(entries):
    size = source.stat().st_size
    chunks.append(f"// {name}\n")
    if size == 0:
      # `unsigned char x[] = {}` is ill-formed, and `#embed` of an empty
      # file expands to nothing -- so an empty resource is represented
      # by no array at all and a null pointer, which is exactly what
      # Resource::data documents.
      chunks.append(f"// (empty -- no array; kR{index} is null)\n\n")
      continue
    chunks.append(f"const unsigned char kR{index}[] = {{\n")
    if embed:
      chunks.append(f'#embed "{source}"\n')
    else:
      chunks.append(array_body(source) + "\n")
    chunks.append("};\n\n")

  chunks.append("// Content digests. Unused by the accessors and never "
                "optimized away as\n"
                "// TEXT: they are what makes this translation unit "
                "change when a\n"
                "// resource's BYTES change, which a #embed back end "
                "otherwise hides from\n"
                "// ccache's direct mode entirely.\n")
  chunks.append("constexpr std::string_view kDigests[] = {\n")
  chunks.extend(line + "\n" for line in digest_lines(entries))
  if not entries:
    chunks.append('    "",\n')
  chunks.append("};\n\n")

  chunks.append("constexpr Resource kAll[] = {\n")
  for index, (name, source) in enumerate(entries):
    empty = source.stat().st_size == 0
    data = "nullptr" if empty else f"kR{index}"
    size = "0" if empty else f"sizeof(kR{index})"
    chunks.append(f"    {{{cxx_string(name)}, "
                  f"{cxx_string(mime_for(name, overrides))}, "
                  f"{data}, {size}}},\n")
  if not entries:
    chunks.append('    {"", "", nullptr, 0},\n')
  chunks.append("};\n")
  chunks.append(f"constexpr std::size_t kCount = {len(entries)};\n")

  chunks.append(f"""
}}  // namespace

std::span<const Resource> all() noexcept {{
  return std::span<const Resource>(kAll, kCount);
}}

const Resource* find(std::string_view name) noexcept {{
  // Sorted by name at generation time, so this is a binary search
  // whatever the set size.
  const std::span<const Resource> resources = all();
  const auto at = std::lower_bound(
      resources.begin(), resources.end(), name,
      [](const Resource& resource, std::string_view wanted) {{
        return resource.name < wanted;
      }});
  if (at == resources.end() || at->name != name) {{
    return nullptr;
  }}
  return &*at;
}}

std::span<const std::byte> get(std::string_view name) noexcept {{
  const Resource* resource = find(name);
  return resource ? resource->bytes() : std::span<const std::byte>();
}}

// Keeps the digest table odr-used from a function nothing calls, so no
// toolchain decides the whole array is dead and drops it before it has
// done its job.
const std::string_view* digests() noexcept {{ return kDigests; }}

{namespace_close(ns)}
""")
  return "".join(chunks)


def write_if_changed(path: Path, text: str) -> None:
  """Rewriting an identical file would restamp its mtime and rebuild
  every TU that includes it, on every configure of every build."""
  if path.exists() and path.read_text(encoding="utf-8") == text:
    return
  path.parent.mkdir(parents=True, exist_ok=True)
  path.write_text(text, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
  parser = argparse.ArgumentParser(
    prog="buildutil.embed", description=__doc__.splitlines()[0])
  parser.add_argument("--manifest", required=True, type=Path)
  parser.add_argument("--header", required=True, type=Path)
  parser.add_argument("--source", required=True, type=Path)
  parser.add_argument("--namespace", required=True)
  parser.add_argument("--mode", required=True, choices=("embed", "array"))
  parser.add_argument("--mime", action="append", default=[],
                      metavar="EXT=TYPE",
                      help="content-type override, e.g. .foo=application/x-foo")
  opts = parser.parse_args(argv)

  overrides = {}
  for pair in opts.mime:
    ext, _, value = pair.partition("=")
    if not ext.startswith(".") or not value:
      return _fail(f"--mime {pair!r} is not '.ext=type'")
    overrides[ext.lower()] = value

  entries = read_manifest(opts.manifest)
  for name, source in entries:
    if not source.is_file():
      return _fail(f"declared resource {name!r} is not a file: {source}")
  entries.sort(key=lambda entry: entry[0])

  write_if_changed(opts.header,
                   header_text(opts.namespace, [n for n, _ in entries]))
  write_if_changed(opts.source,
                   source_text(opts.namespace, entries, overrides,
                               opts.mode == "embed"))
  return 0


def _fail(message: str) -> int:
  print(f"buildutil.embed: {message}", file=sys.stderr)
  return 1


if __name__ == "__main__":
  raise SystemExit(main())
