"""The build's identity: what the stamp records and what the header says.

The stamp half runs real git in a temporary repository -- the shapes
`git describe` produces are the whole point and a faked runner would only
assert the fake.
"""
import json
import os
import re
import subprocess
from pathlib import Path

import pytest

from buildutil import buildinfo, engine

STAMP_TIME = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}Z$")


def _git(repo: Path, *args: str) -> str:
  done = subprocess.run(["git", *args], cwd=repo, capture_output=True,
                        text=True)
  assert done.returncode == 0, done.stdout + done.stderr
  return done.stdout.strip()


def _commit(repo: Path, message: str) -> None:
  _git(repo, "add", "-A")
  _git(repo, "-c", "user.name=Test", "-c", "user.email=test@example.com",
       "commit", "--no-gpg-sign", "-m", message)


@pytest.fixture
def repo(tmp_path, monkeypatch):
  """A one-commit repository the stamp is pointed at."""
  _git(tmp_path, "init", "-b", "main")
  (tmp_path / "file.txt").write_text("one\n")
  _commit(tmp_path, "one")
  monkeypatch.setattr(engine, "REPO_ROOT", tmp_path)
  monkeypatch.setattr(engine, "BDUDATA_DIR", tmp_path / "_bdudata")
  return tmp_path


def _stamped(repo: Path) -> dict:
  engine._stamp_build_info()
  return json.loads((repo / "_bdudata" / "buildinfo.json").read_text())


def _tag(repo: Path, name: str) -> None:
  _git(repo, "-c", "user.name=Test", "-c", "user.email=test@example.com",
       "tag", "-a", name, "-m", name)


def test_an_untagged_commit_describes_as_its_short_hash(repo):
  info = _stamped(repo)
  assert info["version"] == info["commit"] == _git(repo, "rev-parse",
                                                   "--short", "HEAD")
  assert info["tag"] == ""
  assert info["dirty"] is False
  assert info["number"] == 1


def test_a_tag_on_head_is_both_the_version_and_the_tag(repo):
  _tag(repo, "v1.2.3")
  info = _stamped(repo)
  assert info["version"] == "v1.2.3"
  assert info["tag"] == "v1.2.3"


def test_a_commit_after_the_tag_describes_as_the_distance(repo):
  _tag(repo, "v1.2.3")
  (repo / "file.txt").write_text("two\n")
  _commit(repo, "two")
  info = _stamped(repo)
  assert re.fullmatch(r"v1\.2\.3-1-g[0-9a-f]+", info["version"]), info
  assert info["tag"] == ""


def test_a_modified_tracked_file_is_dirty_in_both_readings(repo):
  _tag(repo, "v1.2.3")
  (repo / "file.txt").write_text("edited\n")
  info = _stamped(repo)
  assert info["dirty"] is True
  assert info["version"] == "v1.2.3-dirty"
  # --exact-match answers about the commit, which the edit did not move
  assert info["tag"] == "v1.2.3"


def test_the_time_is_the_minute_in_utc(repo):
  assert STAMP_TIME.fullmatch(_stamped(repo)["time"])


def test_the_build_number_counts_up_from_where_it_was(repo):
  assert [_stamped(repo)["number"] for _ in range(3)] == [1, 2, 3]


def test_a_tree_git_cannot_read_stamps_the_neutral_identity(tmp_path,
                                                            monkeypatch):
  """No repository at all: the keys are still there, and still six."""
  monkeypatch.setattr(engine, "REPO_ROOT", tmp_path)
  monkeypatch.setattr(engine, "BDUDATA_DIR", tmp_path / "_bdudata")
  info = _stamped(tmp_path)
  assert info["commit"] == info["version"] == "unknown"
  assert (info["tag"], info["dirty"], info["number"]) == ("", False, 1)
  assert STAMP_TIME.fullmatch(info["time"])


def test_the_stamp_carries_every_field_the_header_renders(repo):
  assert set(_stamped(repo)) == set(buildinfo.NEUTRAL) | {"package"}


# ------------------------------------------------------------ the header --

STAMP = {"number": 12, "commit": "abc1234", "dirty": True,
         "version": "v0.1.0-3-gabc1234-dirty", "tag": "",
         "time": "2026-09-20T12:34Z"}

HEADER = """\
// Generated by buildutil -- do not edit, and do not commit.
// The build's identity, from _bdudata/buildinfo.json. Included by hand:
// the time moves every build, and a force include would rebuild every TU.
#pragma once

#define DEMO_BUILD_VERSION "v0.1.0-3-gabc1234-dirty"
#define DEMO_BUILD_COMMIT "abc1234"
#define DEMO_BUILD_TAG ""
#define DEMO_BUILD_TIME "2026-09-20T12:34Z"
#define DEMO_BUILD_DIRTY 1
#define DEMO_BUILD_NUMBER 12
"""


def _stamp_file(tmp_path, **changed) -> Path:
  path = tmp_path / "buildinfo.json"
  path.write_text(json.dumps({**STAMP, **changed}))
  return path


def test_the_header_is_the_six_macros_and_nothing_else(tmp_path):
  assert buildinfo.header_text(
    "DEMO", buildinfo.read(_stamp_file(tmp_path))) == HEADER


def test_a_missing_stamp_renders_the_neutral_header(tmp_path):
  text = buildinfo.header_text("DEMO", buildinfo.read(tmp_path / "gone.json"))
  assert '#define DEMO_BUILD_VERSION "unknown"' in text
  assert "#define DEMO_BUILD_DIRTY 0" in text
  assert "#define DEMO_BUILD_NUMBER 0" in text


def test_a_quote_in_a_value_is_refused_rather_than_rendered(tmp_path):
  with pytest.raises(ValueError, match='build tag may not hold \'"\''):
    buildinfo.read(_stamp_file(tmp_path, tag='v1."0'))


def test_a_number_that_is_not_one_is_refused(tmp_path):
  with pytest.raises(ValueError, match="build number is a number"):
    buildinfo.read(_stamp_file(tmp_path, number="many"))


def test_an_unchanged_header_is_not_rewritten(tmp_path):
  """Backdated rather than compared to itself: the box's filesystem
  stamps whole seconds, so two writes a moment apart read identical."""
  header = tmp_path / "generated" / "demo" / "buildinfo.hpp"
  fields = buildinfo.read(_stamp_file(tmp_path))
  buildinfo.write_header(header, "DEMO", fields)
  os.utime(header, (0, 0))
  buildinfo.write_header(header, "DEMO", fields)
  assert header.stat().st_mtime_ns == 0
  buildinfo.write_header(header, "DEMO",
                         buildinfo.read(_stamp_file(tmp_path, number=13)))
  assert header.stat().st_mtime_ns != 0


def test_the_generator_writes_the_header_from_the_stamp(tmp_path):
  header = tmp_path / "buildinfo.hpp"
  assert buildinfo.main(["--prefix", "DEMO",
                         "--input", str(_stamp_file(tmp_path)),
                         "--output", str(header)]) == 0
  assert header.read_text() == HEADER


def test_the_package_version_is_the_last_semver_tag(repo):
  assert _stamped(repo)["package"] == ""
  _tag(repo, "v2.5.1")
  assert _stamped(repo)["package"] == "2.5.1"


def test_an_untagged_tree_has_no_package_version_whatever_was_published(repo):
  """The saved publish base is one clone's history; two clones of one commit stamp alike."""
  (repo / "_bdudata").mkdir()
  (repo / "_bdudata" / "package-version.ini").write_text("base = 4.0.2\nbuild = 3\n")
  assert _stamped(repo)["package"] == ""


def test_the_version_publish_builds_as_is_the_package_version(repo):
  _tag(repo, "v2.5.1")
  engine._stamp_build_info("2.6.0.7")
  assert json.loads((repo / "_bdudata" / "buildinfo.json").read_text())["package"] == "2.6.0.7"


@pytest.mark.parametrize("package, macros", [
  ("7.1.4.9", ['"7.1.4.9"', 7, 1, 4]), ("2.5.1", ['"2.5.1"', 2, 5, 1]),
  ("", ['"0.0.0"', 0, 0, 0]), ("dev", ['"0.0.0"', 0, 0, 0])])
def test_the_package_version_is_four_macros_under_the_define_prefix(tmp_path, package, macros):
  header = tmp_path / "buildinfo.hpp"
  assert buildinfo.main(["--prefix", "DEMO", "--package-prefix", "ACM",
                         "--input", str(_stamp_file(tmp_path, package=package)),
                         "--output", str(header)]) == 0
  names = ["ACM_PACKAGE_VERSION", "ACM_PACKAGE_VERSION_MAJOR", "ACM_PACKAGE_VERSION_MINOR",
           "ACM_PACKAGE_VERSION_PATCH"]
  defines = "".join(f"#define {name} {value}\n" for name, value in zip(names, macros))
  assert header.read_text() == HEADER + defines
